version: "3.7"
volumes:
  client-node_modules:
  server-node_modules:
  postgres-data:

services:

  # node apps
  client:
    build:
      context: .
      dockerfile: client/docker/Dockerfile
    container_name: kadai-client
    environment:
      - COMMAND=${COMMAND:-dev}
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - client/app/.env
    image: kadai:client
    ports:
      - "3001:3000"
    volumes:
      - ./client/app:/app
    tty: true
  
  server:
    build: 
      context: .
      dockerfile: server/docker/Dockerfile
    container_name: kadai-server
    environment:
      - COMMAND=${COMMAND:-dev}
      - NODE_ENV=development
    env_file:
      - server/app/.env
    image: kadai:server
    ports:
      - "3000:3000"
    volumes:
      - ./server/app:/app
    tty: true
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres:12
    container_name: kadai-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - server/app/.env